### PR TITLE
updated build files.

### PR DESCRIPTION
**Pull request by sminogue**
Changes to the master have been made since the last time the combined and minimized jsfeat.js files were last updated. Specifically hough_transform support has been added.

Recommend also tagging a new release for people to use.

### CODE REVIEW

**Comment by serapath** [comment]
There seems to be no conflicts. I'm using a copy of `jsfeat` in another project that I currently refactor.
I would like to remove that copy and instead `require('jsfeat')` directly.

I wrote a message to @inspirit  on twitter here: https://twitter.com/serapath/status/863139445184225280

If @inspirit doesn't maintain this anymore, maybe a fork can be created to include this and maybe the other pull request and maybe some more changes that @mccoder did here: https://github.com/mccoder/clmtrackr/commit/82686b07aa6f46906b88482aa21280dfc1164345

(He described those changes here: https://github.com/auduno/clmtrackr/issues/104#issuecomment-301176602)

It could be published under https://www.npmjs.com/package/js-feat

**Comment by inspirit** [comment]
sorry seems like i did not receive notification for it for some reason...

**Comment by serapath** [comment]
awesome :-)
What about his one? https://github.com/inspirit/jsfeat/pull/18
There was some discussion and it looks like the @ghost added some commits but then nothing happened.

**Is this desireable to be merged or out of scope or why did progress stop?** :-)

I'd just would like to fork the most up2date version in order to make a pull request myself :-)
Would a pull request containing https://github.com/mccoder/clmtrackr/commit/82686b07aa6f46906b88482aa21280dfc1164345 be welcome?
It's about 2 files:
* https://github.com/mccoder/clmtrackr/blob/dev/js/jsfeat_detect.js
* https://github.com/mccoder/clmtrackr/blob/dev/js/jsfeat_detect_worker.js

**Comment by serapath** [comment]
@inspirit oh, and do you mind if i publish the module to npm?
This one: https://www.npmjs.com/package/jsfeat seems to be published by a different guy and a bit outdated too.

**Comment by inspirit** [comment]
the one from #18 can not be merged unfortunately when i saw that pull request the user account was deleted @ghost is just empty name for deleted user. so if you want to have that added you can reopen request with existing user

**Comment by serapath** [comment]
I'm working on a quite serious refactoring of the project. I hope it will get merged.
If it's too much I understand and would just maintain a fork.
It's not done yet, because I have to update the demo's but you can preview already here:
https://github.com/serapath-contribution/jsfeat

The github-page is now served from the `demo/` folder in the master branch and the "gh-pages" branch is removed. You can go to settings in github to change that.
I will try to make all the demos work now and then maybe a pull request makes sense? ...guess that's up to you :-)

**Comment by inspirit** [comment]
so what is the reason for such changes?

**Pull request merged**
